# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab34f0a0d9d5b22b317398dc38b66f0ab5a32ecb90bb3b66c90be2ad2b8e4babce593afadbd28672f5f5595be6d7b6701126ad98ced4e416a5f435852fb4f29

test:
  secret_key_base: 8acd631412c3dede50889f052ae73f4cc8ac7194187a779ff6eb13f87d4c2ef59f0e5846d02d53fa0de33de8a427adca76d2302ffb44fc6fcedc3f5c91bc0409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
